begin;
create or replace function pg_temp.assert_ok(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'TEST FAILED: %',label; end if; end $$;
create function pg_temp.reject(query text) returns void language plpgsql as $$ begin
 begin execute query; exception when others then return; end;
 raise exception 'TEST FAILED: accepted forbidden operation %',query;
end $$;
select set_config('test.owner',gen_random_uuid()::text,true),set_config('test.other',gen_random_uuid()::text,true),set_config('test.champ',gen_random_uuid()::text,true);
insert into auth.users(id,email,aud,role) select current_setting(k)::uuid,current_setting(k)||'@example.invalid','authenticated','authenticated' from unnest(array['test.owner','test.other']) k;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.owner'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.championships(id,owner_id,name,format,max_teams,is_public) values(current_setting('test.champ')::uuid,current_setting('test.owner')::uuid,'Teste grupos','Grupos + mata-mata',8,true);
insert into public.teams(championship_id,name) select current_setting('test.champ')::uuid,'Time '||n from generate_series(1,6)n;
select pg_temp.reject(format('select public.configure_championship_groups(%L,''{}''::jsonb)',current_setting('test.champ')));
select public.configure_championship_groups(current_setting('test.champ')::uuid,(select jsonb_object_agg(id,case when name in ('Time 1','Time 2','Time 3') then 'A' else 'B' end) from public.teams where championship_id=current_setting('test.champ')::uuid));
select public.generate_group_matches(current_setting('test.champ')::uuid);
update public.matches set venue='Quadra A',duration_minutes=60 where championship_id=current_setting('test.champ')::uuid;
select pg_temp.reject(format('update public.matches set duration_minutes=0 where championship_id=%L',current_setting('test.champ')));
select pg_temp.reject(format('update public.matches set venue=repeat(''x'',201) where championship_id=%L',current_setting('test.champ')));
select pg_temp.assert_ok((select count(*)=6 from public.matches where championship_id=current_setting('test.champ')::uuid),'six unique games for two three-team groups');
select pg_temp.assert_ok(not exists(select 1 from public.matches m join public.teams h on h.id=m.home_team_id join public.teams a on a.id=m.away_team_id where m.championship_id=current_setting('test.champ')::uuid and h.group_name<>a.group_name),'no cross-group games');
select pg_temp.assert_ok(not exists(select round,team from (select round,home_team_id team from public.matches where championship_id=current_setting('test.champ')::uuid union all select round,away_team_id from public.matches where championship_id=current_setting('test.champ')::uuid) x group by round,team having count(*)>1),'one game per team per round');
select pg_temp.reject(format('select public.generate_group_matches(%L)',current_setting('test.champ')));
select pg_temp.reject(format('select public.generate_group_knockout(%L)',current_setting('test.champ')));
select pg_temp.reject(format('update public.teams set group_name=''B'' where championship_id=%L and name=''Time 1''',current_setting('test.champ')));
select pg_temp.reject(format('insert into public.teams(championship_id,name) values(%L,''Time extra'')',current_setting('test.champ')));
select pg_temp.reject(format('insert into public.matches(championship_id,home_team_id,away_team_id,round) select championship_id,home_team_id,away_team_id,99 from public.matches where championship_id=%L limit 1',current_setting('test.champ')));
update public.matches set status='finalizado',home_score=1,away_score=0 where championship_id=current_setting('test.champ')::uuid;
-- Missing and cancelled games must prevent qualification even when some games finished.
select set_config('test.match',(select id::text from public.matches where championship_id=current_setting('test.champ')::uuid limit 1),true);
update public.matches set status='cancelado' where id=current_setting('test.match')::uuid;
select pg_temp.reject(format('select public.generate_group_knockout(%L)',current_setting('test.champ')));
update public.matches set status='finalizado' where id=current_setting('test.match')::uuid;
select public.generate_group_knockout(current_setting('test.champ')::uuid);
select pg_temp.assert_ok((select count(*)=2 from public.matches where championship_id=current_setting('test.champ')::uuid and bracket_stage='Semifinal'),'two semifinals');
select pg_temp.assert_ok(not exists(select 1 from public.matches m join private.group_ranking(current_setting('test.champ')::uuid) h on h.team_id=m.home_team_id join private.group_ranking(current_setting('test.champ')::uuid) a on a.team_id=m.away_team_id where m.championship_id=current_setting('test.champ')::uuid and m.bracket_stage='Semifinal' and (h.group_rank<>1 or a.group_rank<>2 or h.group_name=a.group_name)),'first vs second across groups');
select pg_temp.reject(format('select public.generate_group_knockout(%L)',current_setting('test.champ')));
select pg_temp.reject(format('update public.matches set home_score=8 where id=%L',current_setting('test.match')));
select public.save_knockout_result(id,2,0,null,null) from public.matches where championship_id=current_setting('test.champ')::uuid and bracket_stage='Semifinal';
select pg_temp.assert_ok((select count(*)=1 from public.matches where championship_id=current_setting('test.champ')::uuid and bracket_stage='Final'),'group winners progress to final');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.other'),'role','authenticated')::text,true);
select pg_temp.reject(format('select public.generate_group_knockout(%L)',current_setting('test.champ')));
select pg_temp.reject(format('select public.configure_championship_groups(%L,''{}'')',current_setting('test.champ')));
reset role;
set local role anon;
select pg_temp.assert_ok((select count(group_name)=6 from public.teams where championship_id=current_setting('test.champ')::uuid),'anonymous can see public group assignment');
select pg_temp.reject(format('select public.generate_group_matches(%L)',current_setting('test.champ')));
reset role;
select 'group configuration, fixtures, qualification, progression and permissions passed' as test_result;
rollback;
