begin;
create function pg_temp.assert_ok(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'TEST FAILED: %',label; end if; end $$;
create function pg_temp.reject(query text) returns void language plpgsql as $$ begin begin execute query; exception when others then return; end; raise exception 'TEST FAILED: accepted forbidden operation %',query; end $$;
select set_config('test.owner',gen_random_uuid()::text,true),set_config('test.other',gen_random_uuid()::text,true),set_config('test.champ',gen_random_uuid()::text,true);
insert into auth.users(id,email,aud,role) select current_setting(k)::uuid,current_setting(k)||'@example.invalid','authenticated','authenticated' from unnest(array['test.owner','test.other']) k;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.owner'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.championships(id,owner_id,name,format,max_teams,invite_code) values(current_setting('test.champ')::uuid,current_setting('test.owner')::uuid,'Copa auditada','Pontos corridos',4,'SEGREDO');
insert into public.teams(championship_id,name) values(current_setting('test.champ')::uuid,'Azul');
update public.teams set city='Brasília' where championship_id=current_setting('test.champ')::uuid;
select pg_temp.assert_ok((select count(*)=3 from public.audit_logs where championship_id=current_setting('test.champ')::uuid),'insert and update operations audited');
select pg_temp.assert_ok((select bool_and(actor_id=current_setting('test.owner')::uuid) from public.audit_logs where championship_id=current_setting('test.champ')::uuid),'actor captured');
select pg_temp.assert_ok(not exists(select 1 from public.audit_logs where championship_id=current_setting('test.champ')::uuid and details::text like '%SEGREDO%'),'invite code redacted');
select pg_temp.assert_ok((select details->'before'->>'city' is null and details->'after'->>'city'='Brasília' from public.audit_logs where championship_id=current_setting('test.champ')::uuid and entity='teams' and action='update'),'before and after recorded');
select pg_temp.reject(format('delete from public.audit_logs where championship_id=%L',current_setting('test.champ')));
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.other'),'role','authenticated')::text,true);
select pg_temp.assert_ok((select count(*)=0 from public.audit_logs where championship_id=current_setting('test.champ')::uuid),'outsider cannot read audit');
select pg_temp.reject(format('insert into public.audit_logs(entity,action,championship_id) values(''fake'',''insert'',%L)',current_setting('test.champ')));
reset role;
set local role anon;
select pg_temp.assert_ok((select count(*)=0 from public.audit_logs where championship_id=current_setting('test.champ')::uuid),'anonymous cannot read audit');
reset role;
select 'audit ownership, redaction, immutability and actor tracking passed' as test_result;
rollback;
