begin;
create function pg_temp.assert_ok(ok boolean,label text) returns void language plpgsql as $$ begin if ok is distinct from true then raise exception 'TEST FAILED: %',label; end if; end $$;
create function pg_temp.reject(query text) returns void language plpgsql as $$ begin begin execute query; exception when others then return; end; raise exception 'TEST FAILED: accepted forbidden operation %',query; end $$;
select set_config('test.owner',gen_random_uuid()::text,true),set_config('test.member',gen_random_uuid()::text,true),set_config('test.second',gen_random_uuid()::text,true),set_config('test.other',gen_random_uuid()::text,true),set_config('test.champ',gen_random_uuid()::text,true);
insert into auth.users(id,email,aud,role) select current_setting(k)::uuid,current_setting(k)||'@example.invalid','authenticated','authenticated' from unnest(array['test.owner','test.member','test.second','test.other']) k;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.owner'),'role','authenticated')::text,true);
set local role authenticated;
insert into public.championships(id,owner_id,name,format,status,max_teams,is_public,regulations,requires_team_approval,start_date,end_date) values(current_setting('test.champ')::uuid,current_setting('test.owner')::uuid,'Copa inscrições','Pontos corridos','aberto',2,true,'Respeitar os horários.',true,'2026-09-01','2026-09-30');
insert into public.teams(championship_id,name) values(current_setting('test.champ')::uuid,'Time anfitrião');
reset role;
insert into public.championship_members(championship_id,user_id) select current_setting('test.champ')::uuid,current_setting(k)::uuid from unnest(array['test.member','test.second']) k;
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.member'),'role','authenticated')::text,true);
set local role authenticated;
select pg_temp.reject(format('insert into public.teams(championship_id,name,manager_user_id) values(%L,''Sem aprovação'',%L)',current_setting('test.champ'),current_setting('test.member')));
insert into public.team_requests(championship_id,name,short_name,city) values(current_setting('test.champ')::uuid,'Time Azul','AZ','Brasília');
select pg_temp.reject(format('insert into public.team_requests(championship_id,name) values(%L,''Duplicado'')',current_setting('test.champ')));
update public.team_requests set status='approved' where championship_id=current_setting('test.champ')::uuid;
select pg_temp.assert_ok((select bool_and(status='pending') from public.team_requests where championship_id=current_setting('test.champ')::uuid),'applicant cannot approve');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.second'),'role','authenticated')::text,true);
select pg_temp.assert_ok((select count(*)=0 from public.team_requests where championship_id=current_setting('test.champ')::uuid),'other applicant cannot see requests');
insert into public.team_requests(championship_id,name) values(current_setting('test.champ')::uuid,'Time Verde');
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.other'),'role','authenticated')::text,true);
select pg_temp.reject(format('insert into public.team_requests(championship_id,name) values(%L,''Intruso'')',current_setting('test.champ')));
select pg_temp.reject(format('select public.create_championship_edition(%L,''Cópia indevida'',true)',current_setting('test.champ')));
select set_config('request.jwt.claims',json_build_object('sub',current_setting('test.owner'),'role','authenticated')::text,true);
select pg_temp.assert_ok((select count(*)=2 from public.team_requests where championship_id=current_setting('test.champ')::uuid),'owner sees both requests');
update public.team_requests set status='approved' where championship_id=current_setting('test.champ')::uuid and name='Time Azul';
select pg_temp.assert_ok((select count(*)=1 from public.teams where championship_id=current_setting('test.champ')::uuid and name='Time Azul' and manager_user_id=current_setting('test.member')::uuid),'approval creates exactly one team');
select pg_temp.reject(format('update public.team_requests set status=''approved'' where championship_id=%L and name=''Time Azul''',current_setting('test.champ')));
select pg_temp.reject(format('update public.team_requests set status=''approved'' where championship_id=%L and name=''Time Verde''',current_setting('test.champ')));
select pg_temp.assert_ok((select status='pending' and approved_team_id is null from public.team_requests where championship_id=current_setting('test.champ')::uuid and name='Time Verde'),'full capacity rolls back approval');
update public.team_requests set status='rejected' where championship_id=current_setting('test.champ')::uuid and name='Time Verde';
insert into public.players(team_id,name) select id,'Jogador antigo' from public.teams where championship_id=current_setting('test.champ')::uuid limit 1;
insert into public.matches(championship_id,home_team_id,away_team_id,round,status,home_score,away_score) select current_setting('test.champ')::uuid,(array_agg(id order by id))[1],(array_agg(id order by id))[2],1,'finalizado',3,0 from public.teams where championship_id=current_setting('test.champ')::uuid;
select set_config('test.edition',public.create_championship_edition(current_setting('test.champ')::uuid,'Copa nova edição',true)::text,true);
select pg_temp.assert_ok((select status='rascunho' and not is_public and start_date is null and end_date is null and regulations='Respeitar os horários.' and requires_team_approval from public.championships where id=current_setting('test.edition')::uuid),'new edition resets publication and dates, preserves rules');
select pg_temp.assert_ok((select a.invite_code<>b.invite_code and a.public_slug<>b.public_slug from public.championships a,public.championships b where a.id=current_setting('test.champ')::uuid and b.id=current_setting('test.edition')::uuid),'new identifiers for edition');
select pg_temp.assert_ok((select count(*)=2 and bool_and(manager_user_id is null and group_name is null) from public.teams where championship_id=current_setting('test.edition')::uuid),'copy teams without managers and groups');
select pg_temp.assert_ok(not exists(select 1 from public.matches where championship_id=current_setting('test.edition')::uuid) and not exists(select 1 from public.players p join public.teams t on t.id=p.team_id where t.championship_id=current_setting('test.edition')::uuid),'no players or results copied');
select pg_temp.assert_ok((select count(*)=1 from public.matches where championship_id=current_setting('test.champ')::uuid),'source untouched');
reset role;
set local role anon;
select pg_temp.assert_ok((select regulations='Respeitar os horários.' from public.championships where id=current_setting('test.champ')::uuid),'public rules readable');
select pg_temp.reject('select * from public.team_requests');
reset role;
select 'admission approval, capacity, isolation, regulations and clean edition passed' as test_result;
rollback;
