import { useEffect, useMemo, useState } from 'react'
import { RefreshCw, Trophy } from 'lucide-react'
import { supabase } from './lib/supabase'

type C={id:string;name:string;sport:string;format:string;status:string;public_slug:string}
type T={id:string;championship_id:string;name:string;short_name:string|null;city:string|null}
type M={id:string;championship_id:string;home_team_id:string;away_team_id:string;round:number;scheduled_at:string|null;status:string;home_score:number|null;away_score:number|null}

export default function PublicChampionship({slug}:{slug:string}){
 const[c,setC]=useState<C|null>(null),[teams,setTeams]=useState<T[]>([]),[matches,setMatches]=useState<M[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState('')
 async function load(){setLoading(true);setError('');const x=await supabase.from('championships').select('id,name,sport,format,status,public_slug').eq('public_slug',slug).eq('is_public',true).maybeSingle();if(x.error||!x.data){setError(x.error?.message||'Campeonato indisponível.');setLoading(false);return}const[t,m]=await Promise.all([supabase.from('teams').select('id,championship_id,name,short_name,city').eq('championship_id',x.data.id).order('name'),supabase.from('matches').select('id,championship_id,home_team_id,away_team_id,round,scheduled_at,status,home_score,away_score').eq('championship_id',x.data.id).order('round')]);if(t.error||m.error){setError((t.error||m.error)!.message)}else{setC(x.data as C);setTeams((t.data||[]) as T[]);setMatches((m.data||[]) as M[])}setLoading(false)}
 useEffect(()=>{void load()},[slug])
 const table=useMemo(()=>standings(teams,matches),[teams,matches]),name=(id:string)=>teams.find(t=>t.id===id)?.name||'Time'
 if(loading)return <div className="public-center">Carregando…</div>
 if(error||!c)return <div className="public-center"><div className="public-card"><Trophy/><h2>Campeonato indisponível</h2><p>{error}</p><a href="/">Voltar ao Bracketly</a></div></div>
 return <div className="public-page"><header><a href="/"><Trophy size={20}/> Bracketly</a><button onClick={()=>void load()}><RefreshCw size={15}/> Atualizar</button></header><main><section className="public-hero"><span>{label(c.status)}</span><h1>{c.name}</h1><p>{c.sport} · {c.format}</p></section><section className="public-columns"><article className="public-card"><h2>Classificação</h2><div className="public-table"><table><thead><tr><th>#</th><th>Time</th><th>PTS</th><th>J</th><th>V</th><th>E</th><th>D</th><th>SG</th></tr></thead><tbody>{table.map((r,i)=><tr key={r.id}><td>{i+1}</td><td>{r.name}</td><td><b>{r.pts}</b></td><td>{r.j}</td><td>{r.v}</td><td>{r.e}</td><td>{r.d}</td><td>{r.sg}</td></tr>)}</tbody></table></div></article><article className="public-card"><h2>Times</h2>{teams.map(t=><div className="public-team" key={t.id}><b>{t.short_name||t.name.slice(0,3).toUpperCase()}</b><span><strong>{t.name}</strong><small>{t.city||'Cidade não informada'}</small></span></div>)}</article></section><article className="public-card"><h2>Partidas</h2>{matches.length?matches.map(m=><div className="public-match" key={m.id}><span><small>Rodada {m.round}{m.scheduled_at?' · '+new Date(m.scheduled_at).toLocaleString('pt-BR'):''}</small><strong>{name(m.home_team_id)} × {name(m.away_team_id)}</strong></span><b>{m.status==='finalizado'&&m.home_score!==null&&m.away_score!==null?`${m.home_score} × ${m.away_score}`:'Agendado'}</b></div>):<p>Nenhuma partida cadastrada.</p>}</article></main></div>
}
function label(s:string){return s==='aberto'?'Inscrições abertas':s==='em_andamento'?'Em andamento':s==='finalizado'?'Finalizado':'Rascunho'}
function standings(ts:T[],ms:M[]){const a=ts.map(t=>({id:t.id,name:t.name,pts:0,j:0,v:0,e:0,d:0,gp:0,gc:0,sg:0}));const g=(id:string)=>a.find(x=>x.id===id);ms.filter(m=>m.status==='finalizado'&&m.home_score!==null&&m.away_score!==null).forEach(m=>{const h=g(m.home_team_id),v=g(m.away_team_id);if(!h||!v)return;const x=m.home_score!,y=m.away_score!;h.j++;v.j++;h.gp+=x;h.gc+=y;v.gp+=y;v.gc+=x;if(x>y){h.v++;h.pts+=3;v.d++}else if(y>x){v.v++;v.pts+=3;h.d++}else{h.e++;v.e++;h.pts++;v.pts++}});a.forEach(x=>x.sg=x.gp-x.gc);return a.sort((x,y)=>y.pts-x.pts||y.v-x.v||y.sg-x.sg||y.gp-x.gp||x.name.localeCompare(y.name))}
